### ISSUE TITLE
Add support for tm-monitor

### ISSUE THREAD

**Issue by thanethomson** [interchainio/testnets#4]
It'd be great to have [tm-monitor](https://github.com/tendermint/tendermint/tree/master/tools/tm-monitor) optionally enabled for Tendermint testnet deployment.

The first thing would be to add some kind of parameter in the [testnet configuration spec](https://github.com/interchainio/testnets/blob/master/docs/network-layout-spec.md) that would indicate for a particular node group that we want to have `tm-monitor` deployed alongside it. For example:

```yaml
monitoring:
  tm_monitor:
    enabled: yes
    # Must be Linux/AMD64-compatible for the target hosts
    binary: /path/to/locally/built/binary
    # For the -listen-addr parameter to tm-monitor
    listen_addr: "tcp://0.0.0.0:26670"
    # For the -no-ton parameter
    no_ton: no
```

Next we'd have to deploy the `tm-monitor` binary to the Tendermint hosts, possibly by way of adding a `tm_monitor` Ansible role to the [Tendermint Ansible scripts](https://github.com/interchainio/testnets/tree/master/tendermint/ansible). That'd allow us to easily modify the [tmtestnet script](https://github.com/interchainio/testnets/blob/master/tmtestnet.py) to allow for deploying `tm-monitor`.
